### PR TITLE
[DSL-177] retry get currency for holidays

### PR DESCRIPTION
**Pull request by fgchaio**
We need to send the currency to SAP every day, even if it is a Holiday. Because of this, we need to retry the request for getting the currency to previous days.
With these changes, I'm trying to retry the request for a maximum of five previous business days. The first successful request will break the loop and return that value.

Any suggestion is more than welcome!!

### CODE REVIEW

**Comment by nreal** [comment]
I think that this feature is not necessary, as we had discussed it at some point if you want to be run all day we need to change the cron expression  in appsettings.json change "`0 18 * * mon-fri"` by `"0 18 * * *",` and in SAP App you have saved all quotation if you no have quotation return the last quotation

**Comment by fgchaio** [comment]
> if you want to be run all day we need to change the cron expression in appsettings.json change "`0 18 * * mon-fri"` by `"0 18 * * *"`

Sorry I didn't express correctly. I mean only holidays not weekends

**Comment by fgchaio** [comment]
> I think that this feature is not necessary, as we had discussed it at some point if you want to be run all day we need to change the cron expression in appsettings.json change "`0 18 * * mon-fri"` by `"0 18 * * *",` and in SAP App you have saved all quotation if you no have quotation return the last quotation

I'm not sure what you mean by this

**Comment by nreal** [comment]
> > if you want to be run all day we need to change the cron expression in appsettings.json change "`0 18 * * mon-fri"` by `"0 18 * * *"`
> 
> Sorry I didn't express correctly. I mean only holidays not weekends

the job run holiday too

**Comment by fgchaio** [comment]
> > > if you want to be run all day we need to change the cron expression in appsettings.json change "`0 18 * * mon-fri"` by `"0 18 * * *"`
> > 
> > 
> > Sorry I didn't express correctly. I mean only holidays not weekends
> 
> the job run holiday too

of course, but in those cases it only returns a "holiday Error"

**Pull request merged**
